// <auto-generated />
using System;
using Flowspire.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowspire.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250426172858_Migration.v3")]
    partial class Migrationv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("AdvisorCustomer", b =>
                {
                    b.Property<string>("AdvisorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AdvisorId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AdvisorCustomers");

                    b.HasData(
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440002",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440004",
                            AssignedAt = new DateTime(2025, 4, 6, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7966)
                        },
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440002",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440005",
                            AssignedAt = new DateTime(2025, 4, 11, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7966)
                        },
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440003",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440006",
                            AssignedAt = new DateTime(2025, 4, 16, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7966)
                        });
                });

            modelBuilder.Entity("Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Amount = 500.00m,
                            CategoryId = 1,
                            EndDate = new DateTime(2025, 5, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 2, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 120.00m,
                            CategoryId = 2,
                            EndDate = new DateTime(2025, 5, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 2, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 100.00m,
                            CategoryId = 5,
                            EndDate = new DateTime(2025, 6, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 3, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 600.00m,
                            CategoryId = 6,
                            EndDate = new DateTime(2025, 6, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 2, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 200.00m,
                            CategoryId = 3,
                            EndDate = new DateTime(2025, 5, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 1, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 3000.00m,
                            CategoryId = 9,
                            EndDate = new DateTime(2025, 6, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2024, 12, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 200.00m,
                            CategoryId = 10,
                            EndDate = new DateTime(2025, 7, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            StartDate = new DateTime(2025, 3, 26, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7839),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextOccurrence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -80.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 10, 11, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 11, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Supermarket",
                            IsRecurring = false,
                            Notes = "Compras básicas",
                            OriginalAmount = -80.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 11, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 2,
                            Amount = -15.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 10, 16, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 16, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Bus",
                            IsRecurring = false,
                            Notes = "Transporte público",
                            OriginalAmount = -15.00m,
                            PaymentMethod = "Dinheiro",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 16, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2000.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 10, 25, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 25, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Salary",
                            IsRecurring = true,
                            Notes = "Salário mensal",
                            OriginalAmount = 2000.00m,
                            PaymentMethod = "Transferência",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 10, 25, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 4,
                            Amount = -50.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 11, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 11, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Pharmacy",
                            IsRecurring = false,
                            Notes = "Remédios",
                            OriginalAmount = -50.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 11, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 5,
                            Amount = -800.00m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 11, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 11, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Rent",
                            IsRecurring = true,
                            Notes = "Aluguel mensal",
                            OriginalAmount = -800.00m,
                            PaymentMethod = "Transferência",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 11, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 6,
                            Amount = -39.90m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix Subscription",
                            IsRecurring = true,
                            NextOccurrence = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Entretenimento mensal",
                            OriginalAmount = -39.90m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 7,
                            Amount = -22.50m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uber Ride",
                            Fee = 1.50m,
                            IsRecurring = false,
                            Notes = "Corrida rápida",
                            OriginalAmount = -22.50m,
                            PaymentMethod = "Pix",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1800.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Freelance Project",
                            IsRecurring = false,
                            Notes = "Projeto de site",
                            OriginalAmount = 1800.00m,
                            PaymentMethod = "Transferência",
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 20,
                            Amount = -40.00m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 10, 19, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 19, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Cinema",
                            IsRecurring = false,
                            Notes = "Filme em cartaz",
                            OriginalAmount = -40.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 19, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 21,
                            Amount = -150.00m,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 10, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Online Course",
                            IsRecurring = false,
                            Notes = "Curso de investimento",
                            OriginalAmount = -150.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1000.00m,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 10, 24, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 24, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Freelance",
                            IsRecurring = false,
                            Notes = "Serviço de edição",
                            OriginalAmount = 1000.00m,
                            PaymentMethod = "Transferência",
                            Type = 0,
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 23,
                            Amount = -19.90m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spotify Premium",
                            IsRecurring = true,
                            NextOccurrence = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Assinatura mensal",
                            OriginalAmount = -19.90m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 24,
                            Amount = -250.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dentist appointment",
                            Discount = 50.00m,
                            IsRecurring = false,
                            Notes = "Consulta odontológica",
                            OriginalAmount = -250.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 35,
                            Amount = -70.00m,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 10, 14, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 14, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Restaurant",
                            IsRecurring = false,
                            Notes = "Jantar fora",
                            OriginalAmount = -70.00m,
                            PaymentMethod = "Pix",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 14, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 36,
                            Amount = -1500.00m,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 10, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Date = new DateTime(2024, 10, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            Description = "Notebook",
                            IsRecurring = false,
                            Notes = "Compra de notebook",
                            OriginalAmount = -1500.00m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2024, 10, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7680),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 37,
                            Amount = -89.90m,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Udemy Course: C# Clean Architecture",
                            Discount = 40.00m,
                            IsRecurring = false,
                            Notes = "Curso avançado",
                            OriginalAmount = -89.90m,
                            PaymentMethod = "Cartão",
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 38,
                            Amount = 150.00m,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Birthday Gift - Pix Received",
                            IsRecurring = false,
                            Notes = "Presente de aniversário",
                            OriginalAmount = 150.00m,
                            PaymentMethod = "Pix",
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com alimentação e supermercado",
                            IsDefault = true,
                            Name = "Food",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com transporte, combustível e ônibus",
                            IsDefault = true,
                            Name = "Transport",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas médicas e de saúde",
                            IsDefault = true,
                            Name = "Health",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com moradia, aluguel e utilities",
                            IsDefault = true,
                            Name = "Housing",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Entretenimento, restaurantes e lazer",
                            IsDefault = false,
                            Name = "Leisure",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cursos, livros e despesas educacionais",
                            IsDefault = false,
                            Name = "Education",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Roupas e acessórios",
                            IsDefault = false,
                            Name = "Clothing",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com alimentação para outros clientes",
                            IsDefault = true,
                            Name = "Food",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gastos com gadgets, assinaturas e tecnologia",
                            IsDefault = false,
                            Name = "Technology",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com lazer, viagens e entretenimento",
                            IsDefault = false,
                            Name = "Leisure",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Despesas com saúde, academia e consultas",
                            IsDefault = true,
                            Name = "Health",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Investimentos em educação e cursos",
                            IsDefault = true,
                            Name = "Education",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello, I need help with my budget!",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440004",
                            SentAt = new DateTime(2025, 4, 16, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sure, let’s review your expenses.",
                            IsRead = true,
                            ReadAt = new DateTime(2025, 4, 18, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909),
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440004",
                            SenderId = "550e8400-e29b-41d4-a716-446655440002",
                            SentAt = new DateTime(2025, 4, 17, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 3,
                            Content = "What is the best investment now?",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440005",
                            SentAt = new DateTime(2025, 4, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 4,
                            Content = "I recommend index funds.",
                            IsRead = true,
                            ReadAt = new DateTime(2025, 4, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909),
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440005",
                            SenderId = "550e8400-e29b-41d4-a716-446655440002",
                            SentAt = new DateTime(2025, 4, 22, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 5,
                            Content = "How can I reduce my expenses?",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440003",
                            SenderId = "550e8400-e29b-41d4-a716-446655440006",
                            SentAt = new DateTime(2025, 4, 23, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Let's review your categories.",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440006",
                            SenderId = "550e8400-e29b-41d4-a716-446655440003",
                            SentAt = new DateTime(2025, 4, 24, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Thank you for your help!",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440004",
                            SentAt = new DateTime(2025, 4, 25, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Lembre-se de registrar seus investimentos.",
                            IsRead = true,
                            ReadAt = new DateTime(2025, 4, 13, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909),
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440005",
                            SenderId = "550e8400-e29b-41d4-a716-446655440002",
                            SentAt = new DateTime(2025, 4, 12, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Obrigado, acabei de atualizar.",
                            IsRead = true,
                            ReadAt = new DateTime(2025, 4, 14, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909),
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440005",
                            SentAt = new DateTime(2025, 4, 13, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Quero aprender mais sobre reserva de emergência.",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440003",
                            SenderId = "550e8400-e29b-41d4-a716-446655440006",
                            SentAt = new DateTime(2025, 4, 21, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            Id = 11,
                            Content = "Vamos marcar uma call pra isso amanhã?",
                            IsRead = true,
                            ReadAt = new DateTime(2025, 4, 22, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909),
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440006",
                            SenderId = "550e8400-e29b-41d4-a716-446655440003",
                            SentAt = new DateTime(2025, 4, 22, 17, 28, 57, 865, DateTimeKind.Utc).AddTicks(7909)
                        });
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440001",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440002",
                            Name = "FinancialAdvisor",
                            NormalizedName = "FINANCIALADVISOR"
                        },
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440003",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440001",
                            RoleId = "660e8400-e29b-41d4-a716-446655440001"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440002",
                            RoleId = "660e8400-e29b-41d4-a716-446655440002"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440003",
                            RoleId = "660e8400-e29b-41d4-a716-446655440002"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440004",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440005",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440006",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440001",
                            AccessFailedCount = 0,
                            AddressLine1 = "123 Admin St.",
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Admin City",
                            Country = "Admin Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            Gender = 2,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FLOWSPIRE.COM",
                            NormalizedUserName = "ADMIN@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBAJJoYCk8LPD4t7ZLbBYIjz23IMMpT/6DBVM13VglhPsAnm/dUp23Kx5JFp3YhzVg==",
                            PhoneNumber = "+15555550001",
                            PhoneNumberConfirmed = true,
                            PostalCode = "00000",
                            SecurityStamp = "cf24b196-3410-4415-b675-cea21b3d1bbd",
                            State = "Admin State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "admin@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440002",
                            AccessFailedCount = 0,
                            AddressLine1 = "101 Advisor Ave.",
                            BirthDate = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Advisor City",
                            Country = "Advisor Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "advisor1@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Advisor",
                            Gender = 0,
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADVISOR1@FLOWSPIRE.COM",
                            NormalizedUserName = "ADVISOR1@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPo9Zpdq3p51+D46BPz1Pq6hfIcj7nnW6yLGEOTt4UbBRyZkOsIPzDKFE3kzr+FHoQ==",
                            PhoneNumber = "+15555550002",
                            PhoneNumberConfirmed = true,
                            PostalCode = "11111",
                            SecurityStamp = "cbac6059-4884-4885-b84a-16121d28c2a8",
                            State = "Advisor State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "advisor1@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440003",
                            AccessFailedCount = 0,
                            AddressLine1 = "102 Advisor Ave.",
                            BirthDate = new DateTime(1987, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Advisor City",
                            Country = "Advisor Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "advisor2@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Advisor",
                            Gender = 0,
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADVISOR2@FLOWSPIRE.COM",
                            NormalizedUserName = "ADVISOR2@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDzVvy2P+uIN7mSOTeWrGtQ/2xfJNd3lt8eDfTwnX7qiuu1xcT5pydJap+kyA8Oq4w==",
                            PhoneNumber = "+15555550003",
                            PhoneNumberConfirmed = true,
                            PostalCode = "11112",
                            SecurityStamp = "6ca0607c-fd02-4bec-90e7-2f4144f75ed6",
                            State = "Advisor State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "advisor2@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440004",
                            AccessFailedCount = 0,
                            AddressLine1 = "201 Customer Rd.",
                            BirthDate = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Customer City",
                            Country = "Customer Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Customer",
                            Gender = 1,
                            LastName = "One",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER1@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFtWaucrIDmrzL0TrgCbN8iokIRKnMyyxX2wd5xShDA89evcs+wOicLQmENDghKbnw==",
                            PhoneNumber = "+15555550004",
                            PhoneNumberConfirmed = true,
                            PostalCode = "22222",
                            SecurityStamp = "91afa921-f5e8-4f47-b5e8-7e12fb406119",
                            State = "Customer State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "customer1@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440005",
                            AccessFailedCount = 0,
                            AddressLine1 = "202 Customer Rd.",
                            BirthDate = new DateTime(1992, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Customer City",
                            Country = "Customer Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Customer",
                            Gender = 1,
                            LastName = "Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER2@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGlutIPWpgfduJ5Y6BmqChmoEo4z7Puyp8uFN3RoFkuaqhx1p/XxIUSCl+RLe4h/og==",
                            PhoneNumber = "+15555550005",
                            PhoneNumberConfirmed = true,
                            PostalCode = "22223",
                            SecurityStamp = "3c5e77ff-f079-4eea-a707-ed849961cbd0",
                            State = "Customer State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "customer2@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440006",
                            AccessFailedCount = 0,
                            AddressLine1 = "203 Customer Rd.",
                            BirthDate = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Customer City",
                            Country = "Customer Country",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer3@flowspire.com",
                            EmailConfirmed = true,
                            FirstName = "Customer",
                            Gender = 2,
                            LastName = "Three",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER3@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER3@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE6KYS4B+mV9kccIeu/dIeswpr82MtSnESfI1+lQKG5CiozI6XvYQcM5zEs3QH+0TQ==",
                            PhoneNumber = "+15555550006",
                            PhoneNumberConfirmed = true,
                            PostalCode = "22224",
                            SecurityStamp = "601fc86e-0c2c-4e3e-bd92-fa3103f1e9d1",
                            State = "Customer State",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "customer3@flowspire.com"
                        });
                });

            modelBuilder.Entity("AdvisorCustomer", b =>
                {
                    b.HasOne("User", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Budget", b =>
                {
                    b.HasOne("Flowspire.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialTransaction", b =>
                {
                    b.HasOne("Flowspire.Domain.Entities.Category", "Category")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.Category", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.Message", b =>
                {
                    b.HasOne("User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.Category", b =>
                {
                    b.Navigation("FinancialTransactions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("FinancialTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
