// <auto-generated />
using System;
using Flowspire.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowspire.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("AdvisorCustomer", b =>
                {
                    b.Property<string>("AdvisorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AdvisorId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AdvisorCustomers");

                    b.HasData(
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440002",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440004",
                            AssignedAt = new DateTime(2025, 2, 14, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5134)
                        },
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440002",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440005",
                            AssignedAt = new DateTime(2025, 2, 19, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5134)
                        },
                        new
                        {
                            AdvisorId = "550e8400-e29b-41d4-a716-446655440003",
                            CustomerId = "550e8400-e29b-41d4-a716-446655440006",
                            AssignedAt = new DateTime(2025, 2, 24, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5134)
                        });
                });

            modelBuilder.Entity("Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 300.00m,
                            CategoryId = 1,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200.00m,
                            CategoryId = 3,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1000.00m,
                            CategoryId = 4,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150.00m,
                            CategoryId = 5,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 400.00m,
                            CategoryId = 6,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 250.00m,
                            CategoryId = 8,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100.00m,
                            CategoryId = 10,
                            EndDate = new DateTime(2025, 4, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            StartDate = new DateTime(2024, 12, 6, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5000),
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alimentação",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transporte",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Saúde",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Moradia",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lazer",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Educação",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vestuário",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Alimentação",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tecnologia",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lazer",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Olá, preciso de ajuda com meu orçamento!",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440004",
                            SentAt = new DateTime(2025, 2, 24, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Claro, vamos analisar suas despesas.",
                            IsRead = true,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440004",
                            SenderId = "550e8400-e29b-41d4-a716-446655440002",
                            SentAt = new DateTime(2025, 2, 25, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Qual é o melhor investimento agora?",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440002",
                            SenderId = "550e8400-e29b-41d4-a716-446655440005",
                            SentAt = new DateTime(2025, 3, 1, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Recomendo fundos de índice.",
                            IsRead = true,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440005",
                            SenderId = "550e8400-e29b-41d4-a716-446655440002",
                            SentAt = new DateTime(2025, 3, 2, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Como reduzir meus gastos?",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440003",
                            SenderId = "550e8400-e29b-41d4-a716-446655440006",
                            SentAt = new DateTime(2025, 3, 3, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Vamos revisar suas categorias.",
                            IsRead = false,
                            ReceiverId = "550e8400-e29b-41d4-a716-446655440006",
                            SenderId = "550e8400-e29b-41d4-a716-446655440003",
                            SentAt = new DateTime(2025, 3, 4, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(5078)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440001",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440002",
                            Name = "FinancialAdvisor",
                            NormalizedName = "FINANCIALADVISOR"
                        },
                        new
                        {
                            Id = "660e8400-e29b-41d4-a716-446655440003",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440001",
                            RoleId = "660e8400-e29b-41d4-a716-446655440001"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440002",
                            RoleId = "660e8400-e29b-41d4-a716-446655440002"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440003",
                            RoleId = "660e8400-e29b-41d4-a716-446655440002"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440004",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440005",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        },
                        new
                        {
                            UserId = "550e8400-e29b-41d4-a716-446655440006",
                            RoleId = "660e8400-e29b-41d4-a716-446655440003"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -80.00m,
                            CategoryId = 1,
                            Date = new DateTime(2024, 12, 22, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Supermercado",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 2,
                            Amount = -15.00m,
                            CategoryId = 2,
                            Date = new DateTime(2024, 12, 27, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Ônibus",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2000.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 1, 5, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Salário",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 4,
                            Amount = -50.00m,
                            CategoryId = 3,
                            Date = new DateTime(2025, 2, 1, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Farmácia",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 5,
                            Amount = -800.00m,
                            CategoryId = 4,
                            Date = new DateTime(2025, 2, 3, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Aluguel",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 6,
                            Amount = -120.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 1, 27, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Supermercado",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 7,
                            Amount = -60.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 2, 19, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Supermercado",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 8,
                            Amount = -25.00m,
                            CategoryId = 2,
                            Date = new DateTime(2025, 2, 24, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Uber",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 2200.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 3, 5, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Salário",
                            UserId = "550e8400-e29b-41d4-a716-446655440004"
                        },
                        new
                        {
                            Id = 10,
                            Amount = -40.00m,
                            CategoryId = 5,
                            Date = new DateTime(2024, 12, 30, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Cinema",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 11,
                            Amount = -150.00m,
                            CategoryId = 6,
                            Date = new DateTime(2025, 1, 3, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Curso Online",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 1000.00m,
                            CategoryId = 6,
                            Date = new DateTime(2025, 1, 4, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Freelance",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 13,
                            Amount = -90.00m,
                            CategoryId = 7,
                            Date = new DateTime(2025, 2, 1, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Roupas",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 14,
                            Amount = -35.00m,
                            CategoryId = 5,
                            Date = new DateTime(2025, 2, 4, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Cinema",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 15,
                            Amount = -60.00m,
                            CategoryId = 5,
                            Date = new DateTime(2025, 2, 26, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Show",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1200.00m,
                            CategoryId = 6,
                            Date = new DateTime(2025, 3, 5, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Freelance",
                            UserId = "550e8400-e29b-41d4-a716-446655440005"
                        },
                        new
                        {
                            Id = 17,
                            Amount = -70.00m,
                            CategoryId = 8,
                            Date = new DateTime(2024, 12, 25, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Restaurante",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 18,
                            Amount = -1500.00m,
                            CategoryId = 9,
                            Date = new DateTime(2025, 1, 1, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Notebook",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 19,
                            Amount = -50.00m,
                            CategoryId = 10,
                            Date = new DateTime(2025, 1, 27, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Jogo Online",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 20,
                            Amount = -100.00m,
                            CategoryId = 8,
                            Date = new DateTime(2025, 2, 3, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Supermercado",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 21,
                            Amount = -30.00m,
                            CategoryId = 10,
                            Date = new DateTime(2025, 2, 27, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Cinema",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1800.00m,
                            CategoryId = 8,
                            Date = new DateTime(2025, 3, 4, 1, 32, 0, 359, DateTimeKind.Utc).AddTicks(4714),
                            Description = "Salário",
                            UserId = "550e8400-e29b-41d4-a716-446655440006"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440001",
                            AccessFailedCount = 0,
                            Email = "admin@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Admin User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FLOWSPIRE.COM",
                            NormalizedUserName = "ADMIN@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENKIF7gxkoyhwjzx0Y5CRudQxl8D7KtXXupapeUCg6ZUw7aKZeF7JITq52WfIMlctg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5eb9a427-a867-4844-b0f2-b318ba4ce273",
                            TwoFactorEnabled = false,
                            UserName = "admin@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440002",
                            AccessFailedCount = 0,
                            Email = "advisor1@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Advisor One",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADVISOR1@FLOWSPIRE.COM",
                            NormalizedUserName = "ADVISOR1@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIlUS4bXTv3jODtSWuP3/DYVNC7XN3WuDLhD6ZVcUX2o4niAlGGFwzI/+c5OOyrF4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6e5a48c-109f-4712-a239-89f941208eb3",
                            TwoFactorEnabled = false,
                            UserName = "advisor1@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440003",
                            AccessFailedCount = 0,
                            Email = "advisor2@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Advisor Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADVISOR2@FLOWSPIRE.COM",
                            NormalizedUserName = "ADVISOR2@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBHUGfH/RlwvjfgbQLUr7DGFbUhqRqdz4TNBF6Fj7PDUZUHElncUgTfJf52EqzDXLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bff49fb9-01cf-4bf1-91a3-71049170ac83",
                            TwoFactorEnabled = false,
                            UserName = "advisor2@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440004",
                            AccessFailedCount = 0,
                            Email = "customer1@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Customer One",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER1@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER1@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGTCbw1TrPnY7AsjuOfBZdjsMGKjuCVneqjMayEpC68gzBTnOfau5mNcCpXTGgH/7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15b344a1-47bf-480b-a027-73a4332ac100",
                            TwoFactorEnabled = false,
                            UserName = "customer1@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440005",
                            AccessFailedCount = 0,
                            Email = "customer2@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Customer Two",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER2@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER2@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEo0gbdxE13Tfcg3lMjAhhW1UuorzUbC4TB+4p8aJ2xB7UZMflmhICiiENV68WmYng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f6675f4-c14c-44ea-a2a6-dd4e73dc310e",
                            TwoFactorEnabled = false,
                            UserName = "customer2@flowspire.com"
                        },
                        new
                        {
                            Id = "550e8400-e29b-41d4-a716-446655440006",
                            AccessFailedCount = 0,
                            Email = "customer3@flowspire.com",
                            EmailConfirmed = true,
                            FullName = "Customer Three",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER3@FLOWSPIRE.COM",
                            NormalizedUserName = "CUSTOMER3@FLOWSPIRE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENA8MXRiJVad44ANtMfglUb+UC27MAd7Evs/NpuopYg6L8aeKup38M7Y8+GkANVBOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1c547459-021f-479e-81d5-58db0006da86",
                            TwoFactorEnabled = false,
                            UserName = "customer3@flowspire.com"
                        });
                });

            modelBuilder.Entity("AdvisorCustomer", b =>
                {
                    b.HasOne("User", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Budget", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flowspire.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
